### PR TITLE
Making taskwiki multi markup compatible

### PR DESCRIPTION
**Pull request by DancingQuanta**
I am trying to make taskwiki recognise different header syntax of various markups, such as markdown and restructuredtext, and use them as viewports. This is a proposed approach.
I used `CacheRegistry` in `cache.py` as a place to atore the name of the markup in `syntax`. This allows `viewports.py` to query the current markup syntax then select a appropriate regex to match the header of that markup.
I also added a function to `CacheRegistry`, `load_syntax`, to set the markup syntax based on `taskwiki_syntax` to be used for a session. If the `taskwiki_syntax` is not set, then `syntax` will be set to `default` meaning `vimwiki`.
I modified the two test files to test this feature, `base.py` and `test_viewport_parsing.py`. 
In `base.py` I only added `syntax` to `MockCache`.
In `test_viewport_parsing` I created a dictionary of example headers for each markup with string substitution for a viewport.
At the moment this test does not loop over each markup, I only have to select one syntax at the time as I am unsure of how to write the test in the way that each syntax is tested automatically.
So far the test passed for `vimwiki` but not other markups unsurprisingly as I not tested the new regexes rigorously yet.

This is just a proposed concept and can change upon feedback.

### CODE REVIEW

**Comment by tbabej** [comment]
I'm impressed with the quality of this pull request. Overall this looks good, I'm pulling this to a dedicated branch (to push some of my own commits on top).

We will merge this new `extra-syntaxes` branch to master once all tests pass with all syntaxes.

**Comment by tbabej** [comment]
I pushed some fixing commits on top of your work. There were some syntax issues, are you sure you shared the latest code?

Anyway, the current state of the branch at least works for the default syntax. I'm looking forward for the rest of the effort, which will make sure the tests pass with all the syntaxes.

**Comment by DancingQuanta** [comment]
Thank you for considering this PR and I just wanted to show my work before going into more testing to see if you like it so far.
Regarding syntax issues, where are they located?
I find that regexes for the viewport is more tricky with markdown and restructuredtext and will work on this.

**Comment by tbabej** [comment]
I already fixed them, just pull from `extra-syntaxes` branch.

**Comment by DancingQuanta** [comment]
I saw the commits on syntax issues, I replied to that.
Puling the branch causes a merge from origin/master into my extra-syntaxes for me....

**Pull request merged**
