### PR TITLE
Fixed bug that cursor reset when after TaskWikiBufferSave/Load

### PR DESCRIPTION
**Pull request by daizeng1984**
Hi guys, I'm using this plugin on neovim. I think this should be a bug. Every time when I tried to save with plugin enabled, it reset my cursor to beginning of the line. This PR hack solves the problem by saving the cursor and restore it. 

BTW, I tried testing it but it seems task git repo link is broken. After [fixing](https://github.com/daizeng1984/taskwiki/commit/902ad33f4eeeeaf5d13b8e7b5e66adc3a23a97ce) it, it seems to work on Python3.5. master branch's Python2.7 integ test still cannot work.

### CODE REVIEW

**Comment by tbabej** [comment]
This is a nice addition. However, there is no need to hack it like that, you can directly implement saving/restoring the position in WholeBuffer.update_to_tw() and WholeBuffer.update_from_tw().

I'd recommend implementing a method decorator capable of saving/restoring cursor position, and decorating both methods.

**Comment by daizeng1984** [comment]
Thanks Tomas, very nice suggestion! I'll take look at the "decorator" way.

**Comment by daizeng1984** [comment]
Updated the commit @tbabej. Please take a look and let me know if there're any other suggestions. thanks!

**Comment by tbabej** [comment]
This looks great! There is just one nitpick, if you're willing to fix it - the way you wrote the decorator, it will fail when decorating methods that take arguments.

You need to pass the `*args, **kwargs` arguments which expand to all passed positional and keyword arguments, just as it is don in the `pretty_exception_handler` decorator in `taskwiki/errors.py`.

**Comment by daizeng1984** [comment]
Good point! Just updated. 👍 Thanks!

**Comment by tbabej** [comment]
This looks great, thanks!

**Pull request merged**
