### PR TITLE
Allow to configure mapping leader

### PR DESCRIPTION
**Pull request by mrossinek**
This PR add two separate options:
1. `taskwiki_suppress_mappings` which allows the user to completely turn off the map generation by taskwiki.
This is especially useful if one has conflicting mappins or would like to just have a few of them (which can then be set manually in the vimrc).
2. `taskwiki_maplocalleader` which allows to specify a different local leader for all the mappings set by taskwiki (obviously, this only takes affect if the above setting is not used).
This allows a user to specify a different main-mapping to be used for all taskwiki mappings. If this option is not set, it defaults to <Leader>t (just as before).

### CODE REVIEW

**Comment by mrossinek** [comment]
Since I was working on the mappings anyways I figured I could just fix #182 by disallowing remaps. I do not see a reason why this should not be fine here.

**Comment by tbabej** [comment]
This looks great! Could you add some tests? In particular, test that makes sure that remapped leader works, and test that verifies that mappings are supressed.

If you look closely at test implementation, you'll find examples of how to set configuration variables to trigger these changes, and how to simulate user keyboard input.

**Comment by mrossinek** [comment]
Sure thing! Do you have any preferences where I should place them? Shall I create a new file or add them to an existing one (tbh, I am not sure where they would fit in..)

I also noticed that now there is a slight inconsistency in the docs (<leader>t is still mentioned). I will fix that as well.

**Comment by tbabej** [comment]
Either new file or putting it in one of existing is fine. Maybe the new one, I can see the point with the test not fitting any of the filenames.

**Comment by tbabej** [comment]
Travis is broken, but tests are passing locally, thanks for the effort! Merging.

**Comment by tbabej** [comment]
Looks like there are troubles with merging. Rebasing manually.

**Comment by tbabej** [comment]
Merged manually.

**Pull request closed without merging**
