### PR TITLE
VimwikiTask: Stop parent search at smaller indent

### PR DESCRIPTION
**Pull request by canaaerus**
Fix issue #120 

I’d love to add some tests, if you gave me a hint on how to run them. My usual `python -m unittest` does not detect any.

### CODE REVIEW

**Comment by tbabej** [comment]
I'm using py.test, so to run the tests, you can simply do `py.test .` or `python -m pytest`. You will need `gvim` and python packages `vimrunner` and `pytest`.

**Comment by tbabej** [comment]
If you get any problems though, you can always refere to .travis.yml file which has the whole build&test procedure scripted.

**Comment by canaaerus** [comment]
I wonder why you are using a virtual framebuffer and gvim instead of plain vim in the console for the travis tests. Does vimrunner only work with gvim?

**Comment by canaaerus** [comment]
Ok, seems like that is the case. Now on to the testing.

Unfortunately I can’t even get past the sanity tests.
With my locale setting the `messages` command gives
> Übersetzt von Georg Dahn <gorgyd@yahoo.co.uk>

I do have en_GB installed, but not en_US. So while running `LANG=en_US gvim` and calling `messages`, gives
>Messages maintainer: Bram Moolenaar <Bram@vim.org>

I also get a lot of weird errors.

So what I did was comment those lines out. But of course the next sanity check fails as well. There I get the error message
> NameError: name 'cache' is not defined

Maybe that is because is no wiki file was loaded and so neither was taskwiki?

Also: why do you retry the sanity checks 5 times?

Finally I don’t like that the tests are closing my own gvim instance (plain vim is fine though). If I get the tests to run, I might see what I can do about this.

**Comment by tbabej** [comment]
There are certainly reasons for each of these peculiarities. Tests had to be optimized to run on a travis instance which sometimes proved difficult (hence the restarts, or killing of all the gvim sessions). The local-dependant check is a bit unfortunate though.

Nevertheless, we can see on travis that tests for this pull request succeeded. We can add coverage later.

**Pull request merged**
