### PR TITLE
Extra syntaxes: Updated tests with pytest.fixture and conftest.py

### PR DESCRIPTION
**Pull request by DancingQuanta**
To properly test the regexes matching various markups, I made use of pytext.fixture and conftest.py.
This can iterate over markups specified in conftest.py and match a chosen regex against an example markup.

### CODE REVIEW

**Comment by DancingQuanta** [comment]
Don't merge yet, I noticed some mistakes.

**Comment by DancingQuanta** [comment]
I believe this PR is ready to be merged.

**Comment by DancingQuanta** [comment]
I have tried to fix markdown viewport, now working on restructuredtext viewport.

**Comment by DancingQuanta** [comment]
Done with all markup syntaxes!

**Comment by DancingQuanta** [comment]
Hmm, the travis is not happy with taskwarrior make build.

**Comment by tbabej** [comment]
Yes, there is a long term problem with travis. The changes look good, but I did not have a chance to have a deeper look.

We should eventually extend even the declarative tests that use headers to run all the versions of syntaxes. This could be done using some `HEADER(...)` macro in the declaration, which would transparently expand to a header definition before being sent to the vim server.

**Comment by jerri** [comment]
When is this pull request planned to be pushed to master? I would love to use the viewport functionality, but all my wikis are in markdown. Just asking!

**Comment by DancingQuanta** [comment]
Hi @jerri I haven't worked on this for a while. First I need to rebase this pull request on the master which has advanced for a while.
Could you confirm that this pull request adds the functionality you expect for markdown headers please?

**Comment by jerri** [comment]
Just checked it. There is a bug in the markdown-regex for VIEWPORT. A '$' to anchor the regex to the end of line is necessary to get all viewport information. After adding this in 'taskwiki/regex.py' in the VIEWPORT-definition for markdown everything works as expected.

~~~
diff --git a/taskwiki/regexp.py b/taskwiki/regexp.py
index 8457175..214ab13 100644
--- a/taskwiki/regexp.py
+++ b/taskwiki/regexp.py
@@ -87,6 +87,7 @@ VIEWPORT = {
         '(\$(?P<sort>[A-Z]))?'  # Optional sort indicator
         '\s*'                   # Any whitespace
         '([#]+)?'               # Optional Header ending
+        '$'                     # End of line
     ),
     'restructuredtext':
     re.compile(
~~~

**Comment by DancingQuanta** [comment]
Great. Do you use setext headers like this?
```
Section
--------
```

**Comment by jerri** [comment]
Nope. Just the usual ## headers.

**Comment by tbabej** [comment]
@DancingQuanta Nowhere, that's just an idea in my head. To elaborate further, right now tests for taskwiki are pretty nice and declarative, like this:

```
class TestViewportsTaskGeneration(IntegrationTest):

    viminput = """
    === Work tasks | +work ===
    """

    vimoutput = """
    === Work tasks | +work ===
    * [ ] tag work task  #{uuid}
    """

    tasks = [
        dict(description="tag work task", tags=['work']),
    ]

    def execute(self):
        self.command("w", regex="written$", lines=1)
```

in order to supporting testing Markdown syntax without duplicating all the funcitonality, we should do something like:

```
class TestViewportsTaskGeneration(IntegrationTest):

    viminput = """
    HEADER(Work tasks;+work)
    """

    vimoutput = """
    HEADER(Work tasks;+work)
    * [ ] tag work task  #{uuid}
    """

    tasks = [
        dict(description="tag work task", tags=['work']),
    ]

    def execute(self):
        self.command("w", regex="written$", lines=1)
```

which would internally expand the HEADER into two different ways, producing two different test cases.

**Comment by jerri** [comment]
Is there anything I can do to help with this pull request? Would like to have this in master to actually use it. :-)

**Comment by sh78** [comment]
Second @jerri. Wish I was a python-head and could jump in here and save the day, but alas. 

I just discovered taskwarrior, vimwiki, and taskwiki today and 🤯. Would be a game changer to use taskwiki, but thinking in something other than markdown would blow my mind in a less productive way.

**Comment by DancingQuanta** [comment]
I do not have access to a gvim instance and so to test this properly I need the updated `.travis.yml` in the `tbabej:master`. This needs rebasing the `tbabej:extra-syntaxes` branch on the master.

**Comment by DancingQuanta** [comment]
I have applied the macro expansion logic to the `test_viewport_parsing` and `test_viewport` so that this logic is only logic that use the markup syntax information to create the appropriate header for that syntax. So for the future development of the tests, the string for the header and viewports will be `HEADER(<string>)`. The macro expansion will apply the correct syntax around `<string>` for a markup.

**Comment by tbabej** [comment]
@DancingQuanta I rebased the extra-syntaxes branch and fixed travis to run all the tests. All green! After rebasing, pushing to this branch should now properly test your code.

**Comment by DancingQuanta** [comment]
At last I can properly run tests. However `test_viewport.py` are failing only for markdown and restructuredtext but succeeds for vimwiki syntax. This tells me that `taskwiki` have not been configured properly to select the correct parser for markdown and restructuredtext syntax. For this to be resolved, I need to find out why `taskwiki` is not configured as it should.

**Comment by jerri** [comment]
bump?!

**Comment by DancingQuanta** [comment]
@jerri have you used this pull request and have any feedback?
@tbabej Could you rebase your extra-syntaxes on master please?

**Comment by DancingQuanta** [comment]
Ah @tbabej have added `Preset header` so rebasing `tbabej/taskwiki/extra-syntaxes` onto `tbabej/taskwiki/master` needs some work.

**Comment by tbabej** [comment]
@DancingQuanta header_start is the match group in the regex that matches the beggining of the header

    === Work tasks | + work ===
    ^^^ this is header_start

    ### Work tasks
    ^^^ this should be also header_start

**Comment by tbabej** [comment]
Sorry for not rebasing yet, I'm currently very overwhelmed with tasks and projects.

**Comment by DancingQuanta** [comment]
Could I rebase and create a new pull request? `regexp.py` needs some work to make `preset_header` work for other markups.

**Comment by DancingQuanta** [comment]
The `header_start` is tricky for restructuredtext headers because they use underlines that have no absolute header level, only relative. So only vimwiki and markdown can support preset for now.

**Comment by DancingQuanta** [comment]
Closed as superseded by a newer pull-request #192 to work on master

**Pull request closed without merging**
